fix: add openshift-local release v1.4.0 to extensions catalog
containers/podman-desktop-catalog pull request #61
Opened 2024-08-13 01:38 UTC by dgolovin

2024-08-27 02:33 UTC, dgolovin commented on api/extensions.json
> +          "ociUri": "quay.io/redhat-developer/openshift-local-extension:v1.4.0",
```suggestion
          "ociUri": "ghcr.io/crc-org/crc-extension:1.4.0",
```

2024-08-27 02:34 UTC, dgolovin commented on api/extensions.json
> +          "ociUri": "quay.io/redhat-developer/openshift-local-extension:v1.4.0",
CC: @jeffmaury

2024-08-27 18:41 UTC, dgolovin commented on api/extensions.json
> +          "version": "1.4.0",
```suggestion
          "version": "2.0.0",
```

2024-08-28 06:47 UTC, jeffmaury requested changes
Folder needs also to be renamed

2024-08-28 06:47 UTC, jeffmaury commented on api/extensions.json
> +              "data": "https://registry.podman-desktop.io/api/extensions/redhat/openshift-local/1.4.0/icon.png"
Should be 2.0.0

2024-08-28 06:47 UTC, jeffmaury commented on api/extensions.json
> +              "data": "https://registry.podman-desktop.io/api/extensions/redhat/openshift-local/1.4.0/README.md"
Idem

2024-08-28 06:47 UTC, jeffmaury commented on api/extensions.json
> +              "data": "https://registry.podman-desktop.io/api/extensions/redhat/openshift-local/1.4.0/LICENSE.txt"
Idem

2024-08-28 23:29 UTC, dgolovin reviewed
We got an approval from QA team https://github.com/containers/podman-desktop/issues/8372

2024-08-29 07:11 UTC, jeffmaury approved these changes
LGTM

2024-08-29 15:50 UTC, merged